version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: projis-front
    container_name: projis-front
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/frontend
    depends_on:
      - backend
    network_mode: host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: proji-back
    container_name: proji-back
    restart: always
    ports:
      - 3333:3333
    volumes:
      - ./backend:/usr/backend
    env_file:
      - ./backend/.env.dev
    depends_on:
      - database
    network_mode: host

  database:
    image: postgres
    container_name: postgres-docker
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projisdb
    volumes:
      - pgdata:/data/postgres
    network_mode: host

volumes:
  pgdata:
    driver: local
