version: "3.7"

services:
  app:
    build: .
    image: proji
    container_name: proji-api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    env_file:
      - .env.dev
    depends_on:
      - database
    network_mode: host

  database:
    image: postgres
    container_name: postgres-docker
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projisdb
    volumes:
      - pgdata:/data/postgres
    network_mode: host

volumes:
  pgdata:
    driver: local
